TOP=../..

include $(TOP)/configure/CONFIG

PROD += SQCCommand

#PROD_IOC = SQC-310

# SQC-310.dbd will be installed into <top>/dbd
DBD += SQC-310.dbd

# SQC-310.dbd will be created from these files
SQC-310_DBD += base.dbd
#SQC-310_DBD += xxx.dbd

# We need to link this IOC Application against the EPICS Bas

include $(TOP)/configure/RULES
